version: 2
jobs:
machine:
  python:
    version: 2.7.10

dependencies:
  pre:
    - pip install ansible
    - pip install setuptools==39.2.0
    - pip install ansible-container[docker,openshift]




#  build:
#    docker:
#      - image: debian:stretch
#    steps:
#      - checkout
#      - run:
#          name: Greeting
#          command: echo Hello, world.
#      - run:
#          name: Print the Current Time
#          command: date
